# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

[^1] 
menu:
[^2]- {name: 'Ramen',  url: 'Ramen'}
[^3]- {name: 'Bar', url: 'Bar'}
[^4]- {name: 'Sport',       url: 'Sport'}
[^5]- {name: 'High school',      url: 'High school'}
[^6]- {name: 'About',              url: 'about'}
[^7]- {name: 'Contact',            url: 'contact'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:

- {icon: 'facebook', link:   'https://www.facebook.com/people/%E5%A4%9C%E5%85%89%E9%96%83%E4%BA%AE%E4%BA%AE%E5%BE%A9%E4%BB%87%E9%AC%BC/100011292037726/'}
- {icon: 'instagram', link:  'https://www.instagram.com/yuan_.c/'}
- {icon: 'envelope', link:   'mailto:anngood0205@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
